name: Angular CI/CD

on:
  push:
    branches:
      - main # or the name of your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the version of Node.js you want here

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: ng build --configuration=production --base-href "/AppUI/"
        env:
          NEXTECH_TOKEN: ${{ secrets.NEXTECH_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          repository-name: "VCrishna/AppUI"
          access-token: ${{ secrets.NEXTECH_TOKEN }}
          branch: gh-pages
          folder: dist/krishna-proj
